// PenTool.cpp — NDK plugin entry point
//
// This translation unit is intentionally minimal. All logic lives in
// AnnotationNode and PenOverlay. We simply ensure the plugin is initialised
// cleanly and its Op Description is registered with Nuke's factory.
//
// Nuke calls MMSInit() (or MMSLoaded() on some versions) once when the
// shared library is first loaded.
//
// Windows: symbols are exported via PenTool.def (generated by CMake).
// The PENTOOL_EXPORT macro provides a safety-net __declspec(dllexport) in
// case the .def file is not used.

#include "AnnotationNode.h"

#include <cstdio>

#ifdef _WIN32
#  define PENTOOL_EXPORT __declspec(dllexport)
#else
#  define PENTOOL_EXPORT __attribute__((visibility("default")))
#endif

extern "C"
{

PENTOOL_EXPORT void MMSInit()
{
    // Touch the static Description object so the linker cannot dead-strip it.
    (void)AnnotationNode::desc;

    std::fprintf(stdout,
        "[PenTool] Plugin loaded.\n"
        "  * AnnotationNode available under Other/ in the node menu.\n"
        "  * Edit > Pen Tool  or  Ctrl+Shift+P  to draw on the graph.\n");
    std::fflush(stdout);
}

// Some Nuke versions call MMSLoaded instead of (or in addition to) MMSInit.
PENTOOL_EXPORT void MMSLoaded() { MMSInit(); }

} // extern "C"
